# -*- coding: utf-8 -*-
"""coleta_limpeza_falas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaj_nIM4SDAajTphGD7KXaQ6hlm96CBq
"""

import requests
import pandas as pd

autor_fala = []
fala = []

def coleta_notas(dado2):
  for link in dado2:
    url3 = link
    resposta3 = requests.get(url3)
    html3 = resposta3.text
    texto3 = html3.replace('</span></div></div><div><div class="principalStyle">', '')
    texto3 = texto3.replace('</span></div><div class="principalStyle"><span>', '')
    texto3 = texto3.replace('</span><span class="intercorrenciaMesmoSegmentoStyle">', '')
    texto3 = texto3.replace('</span><span class="principalStyle">', '')
    texto3 = texto3.replace('</span></div></div><div><div class="anotacaoAberturaStyle"><span>(<i>S', '')
    texto3 = texto3.replace('</span></div></div><div><div class="intercorrenciaCentralizadoStyle"><span>(<i>Tumulto no recinto.</i>)', '') 
    texto3 = texto3.replace('</span></div></div><div><div class="intercorrenciaCentralizadoStyle"><span>(<i>Soa a campainha.</i>)', '') 
    texto3 = texto3.replace('(<i>Pausa.</i>) <span', '')
    texto3 = texto3.replace('</span></div></div><div><div class="intercorrenciaCentralizadoStyle"><span>(<i>Interrupção do som.</i>) (<i>Pausa.</i>)','')
    texto3 = texto3.replace('O SR.','')
    texto3 = texto3.replace('A SRA.','')
    texto3 = texto3.replace('</b>','')
    texto3 = texto3.replace('(<i>Risos.</i>)','')
    texto3 = texto3.replace('<span>', '')
    texto3 = texto3.replace('</span></div></div><div><div class="anotacaoOcorrenciaStyle"><span>(<i>Procede-se à exibição de vídeo.</i>)', '')
    partes3 = texto3.split('<b>')
    for item in partes3[1:]:
      partes4 = item.split(') – ')
      if len(partes4) > 1:
        autor_fala.append(partes4)
        fala.append(partes4[1])

coleta_notas(lista2)

df = pd.DataFrame(fala, columns=['fala'])
dados = df.to_csv('cpi.csv')

df2 = pd.DataFrame(autor_fala, columns=['autor', 'fala', 'outro'])
dados2 = df2.to_csv('cpi_completa.csv')