# -*- coding: utf-8 -*-
"""coleta_sites_notas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgNW7x4zKUAxjVnQjhtz9GhOoQRoICey
"""

import requests

lista2 = []

def coleta_notas(dados):
  for codigo in dados:
    url2 = "https://legis.senado.leg.br/dadosabertos/reuniaocomissao/notas/" + str(codigo)
    resposta2 = requests.get(url2)
    html2 = resposta2.text
    parte = []
    partes2 = html2.split('<UrlNotasTaquigraficas>')
    if len(partes2) > 1:
      partes2 = partes2[1]
      subpartes2 = partes2.split('</UrlNotasTaquigraficas>')
      lista2.append(subpartes2[0])
    else:
      continue

coleta_notas()