# -*- coding: utf-8 -*-
"""notas_cpicovid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3dKQh7cRuew3stgeQ68YtRU6nWjhKIm
"""

import requests

"""# Coleta do código das sessões da CPI"""

url = "https://legis.senado.leg.br/comissoes/comissao?codcol=2441&data1=2021-01-01&data2=2021-10-21"
resposta = requests.get(url)
html = resposta.text
print(html)

lista = []
partes = html.split('<a href="./reuniao?reuniao=')

def coleta_dados():
  for parte in partes:
    subpartes = parte.split('&amp;codcol=2441">')
    conteudo = subpartes[0]
    if len(conteudo) > 10:
      continue 
    if conteudo not in lista:
      lista.append(conteudo)
  print(lista)

coleta_dados()

"""# Coleta site onde estão as notas taquigráficas"""

lista2 = []

def coleta_notas(dados):
  for codigo in dados:
    url2 = "https://legis.senado.leg.br/dadosabertos/reuniaocomissao/notas/" + str(codigo)
    resposta2 = requests.get(url2)
    html2 = resposta2.text
    parte = []
    partes2 = html2.split('<UrlNotasTaquigraficas>')
    if len(partes2) > 1:
      partes2 = partes2[1]
      subpartes2 = partes2.split('</UrlNotasTaquigraficas>')
      lista2.append(subpartes2[0])
    else:
      continue

coleta_notas(lista)

print(lista2)

"""# Coleta notas taquigráficas"""

autor_fala = []
fala = []

def coleta_notas(dado2):
  for link in dado2:
    url3 = link
    resposta3 = requests.get(url3)
    html3 = resposta3.text
    texto3 = html3.replace('</span></div></div><div><div class="principalStyle">', '')
    texto3 = texto3.replace('</span></div><div class="principalStyle"><span>', '')
    texto3 = texto3.replace('</span><span class="intercorrenciaMesmoSegmentoStyle">', '')
    texto3 = texto3.replace('</span><span class="principalStyle">', '')
    texto3 = texto3.replace('</span></div></div><div><div class="anotacaoAberturaStyle"><span>(<i>S', '')
    texto3 = texto3.replace('</span></div></div><div><div class="intercorrenciaCentralizadoStyle"><span>(<i>Tumulto no recinto.</i>)', '') 
    texto3 = texto3.replace('</span></div></div><div><div class="intercorrenciaCentralizadoStyle"><span>(<i>Soa a campainha.</i>)', '') 
    texto3 = texto3.replace('(<i>Pausa.</i>) <span', '')
    texto3 = texto3.replace('</span></div></div><div><div class="intercorrenciaCentralizadoStyle"><span>(<i>Interrupção do som.</i>) (<i>Pausa.</i>)','')
    texto3 = texto3.replace('O SR.','')
    texto3 = texto3.replace('A SRA.','')
    texto3 = texto3.replace('</b>','')
    texto3 = texto3.replace('(<i>Risos.</i>)','')
    texto3 = texto3.replace('<span>', '')
    texto3 = texto3.replace('</span></div></div><div><div class="anotacaoOcorrenciaStyle"><span>(<i>Procede-se à exibição de vídeo.</i>)', '')
    partes3 = texto3.split('<b>')
    for item in partes3[1:]:
      partes4 = item.split(') – ')
      if len(partes4) > 1:
        autor_fala.append(partes4)
        fala.append(partes4[1])

coleta_notas(lista2)

import pandas as pd
df = pd.DataFrame(fala, columns=['fala'])
dados = df.to_csv('cpi.csv')

df2 = pd.DataFrame(autor_fala, columns=['autor', 'fala', 'outro'])
dados2 = df2.to_csv('cpi_completa.csv')

s =','.join([str(item) for item in fala])

from collections import Counter

for char in '-.,\n':
    s = s.replace(char, ' ')
s = s.lower()
palavras = s.split()

print(Counter(palavras).most_common())

def word_count(dado):
    counts = dict()
    for word in dado:
        if word in counts:
          if len(word) > 2: 
            counts[word] += 1
        else:
            counts[word] = 1
    return counts

print( word_count(palavras))